# Generated by Django 3.1 on 2020-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todos', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='shift',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('AM', 'AM')], max_length=5, null=True),
        ),
    ]
